config/routes.rb
WhoGotMy::Application.routes.draw do
  resources :items
  resources :locations
  resources :categories

  root :to => 'items#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :items
  validates :title, :presence => true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :location
  has_and_belongs_to_many :categories

  validates :name, :presence => true
  validates :rating, :inclusion => {:in => 1..5}
  
  scope :highest_rating, order("rating desc")
  scope :top5_rating, highest_rating.limit(5)
  
end

app/models/location.rb
class Location < ActiveRecord::Base
   has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ActionController::Base
  def index
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, :notice => 'Item was successfully created.' }
        format.json { render :json => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, :notice => 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
  
  def search
  @result= Item.where("name LIKE ?","%#{params[:id]})
  respond_to do |format|
    format.json {render :json => @result}
  end
end
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :borrower %><br />
    <%= f.text_field :borrower %>
  </div>
<div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.haml
%h1 Editing item

=render 'form'

=link_to 'Show', @item
=link_to 'Back', items_path

app/views/categories/index.html.haml
%h1 Listing items
=link_to 'New Item', new_item_path
%table
  %tr
    %th Name
    %th Description
    %th Rating
    %th Location
    %th Borrower
    %th 
    
  -@items.each do |item|
    %tr
      %td=link_to item.name, item
      %td=item.description
      %td=item.rating
      %td=item.location.title if item.location 
      %td=item.borrower
      %td=link_to 'Edit', edit_item_path(item)
      %td=link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete

app/views/categories/new.html.erb
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/categories/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Borrower:</b>
  <%= @item.borrower %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/edit.html.haml
%h1 Editing item

=render 'form'

=link_to 'Show', @item
=link_to 'Back', items_path

app/views/items/index.html.haml
%h1 Listing items
=link_to 'New Item', new_item_path
%table
  %tr
    %th Name
    %th Description
    %th Rating
    %th Location
    %th Borrower
    %th 
    
  -@items.each do |item|
    %tr
      %td=link_to item.name, item
      %td=item.description
      %td=item.rating
      %td=item.location.title if item.location 
      %td=item.borrower
      %td=link_to 'Edit', edit_item_path(item)
      %td=link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/layouts/_header.html.haml
%header
  %logo
    = link_to image_tag("rails.png"), root_path
  %ul
    %li= link_to "My Items", root_path
    %li= link_to "Categories", categories_path
    %li= link_to "Locations", locations_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title WhoGotMy
    =stylesheet_link_tag    "application", :media => "all"
    =javascript_include_tag "application"
    =csrf_meta_tags
  %body
    = render :partial => "layouts/header"  
    = yield